### ISSUE TITLE
OS support

### ISSUE THREAD

**Issue by alessio-b-zak** [bergercookie/taskw_gcal_sync#11]
Hi there,

What is the current limitation driving the usage only on Linux?

**Comment by bergercookie** [comment]
I suppose there's no real constraint.
I've been running and testing this on Linux, but I suppose it could also work on MacOs or any other platform that `taskwarrior` supports.

What's your target OS? You could try running it on your machine and if you find that something doesn't work open an issue.

**Comment by alessio-b-zak** [comment]
Just thinking about MacOS. Thought it might be something to do with path wrangling. Will give it a go and report back :)

**Comment by alessio-b-zak** [comment]
Can confirm that works on MacOS Mojave 10.14.5 when you remove the check in the PrefsManager file!

**Comment by bergercookie** [comment]
Cool, thanks,
Will have to relax that assertion then

**Comment by alessio-b-zak** [comment]
Although when modifying a task to have a due date and then syncing I got the following error, however not sure if this is a generic bug or an OS specific bug.

```
Traceback (most recent call last):
  File "/USERS/intern1/Library/Python/3.7/bin/tw_gcal_sync", line 61, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/USERS/intern1/Library/Python/3.7/bin/tw_gcal_sync", line 53, in main
    aggregator.register_items(gcal_items, "gcal")
  File "/Users/intern1/Library/Python/3.7/lib/python/site-packages/taskw_gcal_sync/TWGCalAggregator.py", line 249, in register_items
    other_item_new = convert_fun(item)
  File "/Users/intern1/Library/Python/3.7/lib/python/site-packages/taskw_gcal_sync/TWGCalAggregator.py", line 512, in convert_gcal_to_tw
    tw_item['due'] = GCalSide.get_event_time(gcal_item, t='end')
  File "/Users/intern1/Library/Python/3.7/lib/python/site-packages/taskw_gcal_sync/GCalSide.py", line 223, in get_event_time
    item[t][GCalSide.get_date_key(item[t])])
  File "/Users/intern1/Library/Python/3.7/lib/python/site-packages/taskw_gcal_sync/GCalSide.py", line 271, in parse_datetime
    dt_out = datetime.datetime.strptime(dt2, _format)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2019-09-04T16:52:42+01:0.000000Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

However I'm

**Comment by bergercookie** [comment]
This is probably a bug.

This is a strange format for timedate.
Do you know what event this Google calendar event this is coming from? What timezone is that event in?

**Comment by alessio-b-zak** [comment]
I created the event in tadkwarrior without a due date, then synced to
Google calendar, then added a due date and then synced back. I'm currently
in GMT+1. I'll have a dig through the code myself to check too.

**Comment by alessio-b-zak** [comment]
Yeah it does seem like daylight savings has ruined yet another thing

**Comment by bergercookie** [comment]
OK, yeah, should be simple to solve.
But just to clarify, what was your local time was it when you created that event? Was it 16:52? Or maybe it was 15:52 and one is supposed to add 1 more hour to reach GMT?

**Comment by bergercookie** [comment]
- [ ] Solve different timezone bug + doctest
- [ ] Relax PrefsManager assertion

**Comment by alessio-b-zak** [comment]
Err I think it was 16:52. I'm in the U.K. at the moment so unsure. I'll try and spit out a few more date formats to see.

**Comment by alessio-b-zak** [comment]
Just as a pointer that I've managed to parse the timedate using the `arrow` library.

```
import arrow

x = '2019-09-04T16:52:42+01:0.000000Z'

print(arrow.get(x).datetime)
```
Which prints out

```
>>> 2019-09-04 16:52:42+01:00
```

**Comment by bergercookie** [comment]
Sorry for the delay,
Will deal with it, hopefully during the weekend if I get some time.

**Comment by bergercookie** [comment]
@alessio-b-zak `arrow` looks great btw, will start using ti instead of `timedate`!
