### ISSUE TITLE
ValueError: time data '2019-09-04T16:52:42+01:0.000000Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

### ISSUE THREAD

**Issue by bergercookie** [bergercookie/taskw_gcal_sync#13]
Although when modifying a task to have a due date and then syncing I got the following error, however not sure if this is a generic bug or an OS specific bug.

```
Traceback (most recent call last):
  File "/USERS/intern1/Library/Python/3.7/bin/tw_gcal_sync", line 61, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/USERS/intern1/Library/Python/3.7/bin/tw_gcal_sync", line 53, in main
    aggregator.register_items(gcal_items, "gcal")
  File "/Users/intern1/Library/Python/3.7/lib/python/site-packages/taskw_gcal_sync/TWGCalAggregator.py", line 249, in register_items
    other_item_new = convert_fun(item)
  File "/Users/intern1/Library/Python/3.7/lib/python/site-packages/taskw_gcal_sync/TWGCalAggregator.py", line 512, in convert_gcal_to_tw
    tw_item['due'] = GCalSide.get_event_time(gcal_item, t='end')
  File "/Users/intern1/Library/Python/3.7/lib/python/site-packages/taskw_gcal_sync/GCalSide.py", line 223, in get_event_time
    item[t][GCalSide.get_date_key(item[t])])
  File "/Users/intern1/Library/Python/3.7/lib/python/site-packages/taskw_gcal_sync/GCalSide.py", line 271, in parse_datetime
    dt_out = datetime.datetime.strptime(dt2, _format)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '2019-09-04T16:52:42+01:0.000000Z' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'
```

_Originally posted by @alessio-b-zak in https://github.com/bergercookie/taskw_gcal_sync/issues/11#issuecomment-527947377_

- [ ] Solve datetime issue
- [ ] Consider switching from `timedate` usage to `arrow`

**Comment by bergercookie** [comment]
@alessio-b-zak, unfortunately I can't reproduce it.
I fixed a push to the GCalSide class though so that it can handle the format that was breaking.

Let me know if this still doesn't work.
