### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by grovesteyn** [bergercookie/taskw_gcal_sync#14]
Hi
I really want to try this out, but It fails on the sync. It looks like a json problem. Do you have any suggestions?

```
Traceback (most recent call last):
  File "/home/grove/.local/bin/tw_gcal_sync", line 61, in <module>
    main()
  File "/home/grove/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/grove/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/grove/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/grove/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/grove/.local/bin/tw_gcal_sync", line 46, in main
    use_ascending_order=ascending_order)
  File "/home/grove/.local/lib/python3.6/site-packages/taskw_gcal_sync/TaskWarriorSide.py", line 54, in get_all_items
    self._load_all_items()
  File "/home/grove/.local/lib/python3.6/site-packages/taskw_gcal_sync/TaskWarriorSide.py", line 38, in _load_all_items
    self.items = self.tw.load_tasks()
  File "/usr/local/lib/python3.6/dist-packages/taskw/warrior.py", line 553, in load_tasks
    for db in Command.files(command)
  File "/usr/local/lib/python3.6/dist-packages/taskw/warrior.py", line 553, in <genexpr>
    for db in Command.files(command)
  File "/usr/local/lib/python3.6/dist-packages/taskw/warrior.py", line 489, in _get_task_objects
    json = self._get_json(*args)
  File "/usr/local/lib/python3.6/dist-packages/taskw/warrior.py", line 486, in _get_json
    return json.loads(decoded)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 125 column 511 (char 34179)

```

**Comment by bergercookie** [comment]
Hi @grovesteyn ,

Thanks for the interest.
It crashes at the lines of another project, `taskw`.
Just to verify, have you installed taskw via my package's requirements or manually?

Can you make sure you have installed this package as follows:
```
git clone https://github.com/bergercookie/taskw_gcal_sync
cd taskw_gcal_sync
git checkout master
pip3 install --user --upgrade -r requirements.txt
```

Taking a look at the output, it seems like the installed json decoding operation crashes:

```
  File "/usr/local/lib/python3.6/dist-packages/taskw/warrior.py", line 489, in _get_task_objects
    json = self._get_json(*args)
```

What's the character that it's trying to decode? Perhaps use `pdb` to go into either of the following lines and print the json /character contents?

* File "/usr/local/lib/python3.6/dist-packages/taskw/warrior.py", line 486, in _get_json
* File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode

**Comment by grovesteyn** [comment]
Hi @bergercookie 

Thanks for this.  I have now ensured that I have the git installation as you suggest.  I now seem to run into an authentication error before I can even get to the json issues.  Any suggestions?


```
tw_gcal_sync -t remind -c "MyTasks"
__main__: 2019-11-11 13:52:30 - INFO     - Initialising...
GCalSide: 2019-11-11 13:52:30 - INFO     - Connecting...
GCalSide: 2019-11-11 13:52:30 - INFO     - Invalid credentials. Fetching them...

TaskWarrior
-----------
	* Tasks created: 0
	* Tasks updated: 0
	* Tasks deleted: 0
	* Errors:        0

Google Calendar
---------------
	* Tasks created: 0
	* Tasks updated: 0
	* Tasks deleted: 0
	* Errors:        0

Traceback (most recent call last):
  File "/home/grove/.local/bin/tw_gcal_sync", line 71, in <module>
    main()
  File "/home/grove/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/grove/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/grove/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/grove/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/grove/.local/bin/tw_gcal_sync", line 50, in main
    aggregator.start()
  File "/home/grove/.local/lib/python3.6/site-packages/taskw_gcal_sync/TWGCalAggregator.py", line 131, in start
    self.gcal_side.start()
  File "/home/grove/.local/lib/python3.6/site-packages/taskw_gcal_sync/GCalSide.py", line 55, in start
    self.gain_access()
  File "/home/grove/.local/lib/python3.6/site-packages/taskw_gcal_sync/GCalSide.py", line 213, in gain_access
    creds = self._get_credentials()
  File "/home/grove/.local/lib/python3.6/site-packages/taskw_gcal_sync/GCalSide.py", line 195, in _get_credentials
    creds.refresh(Request())
  File "/home/grove/.local/lib/python3.6/site-packages/google/oauth2/credentials.py", line 152, in refresh
    self._scopes,
  File "/home/grove/.local/lib/python3.6/site-packages/google/oauth2/_client.py", line 241, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/grove/.local/lib/python3.6/site-packages/google/oauth2/_client.py", line 115, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/grove/.local/lib/python3.6/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_scope: Some requested scopes were invalid. {invalid=[a, c, d, e, g, h, i, l, m, ., n, /, o, p, r, s, t, u, w, :]}', '{\n  "error": "invalid_scope",\n  "error_description": "Some requested scopes were invalid. {invalid\\u003d[a, c, d, e, g, h, i, l, m, ., n, /, o, p, r, s, t, u, w, :]}",\n  "error_uri": "http://code.google.com/apis/accounts/docs/OAuth2.html"\n}')


```

**Comment by bergercookie** [comment]
Can you first clean the credentials cache and the taskw_gcal_sync task and rerun it?

```
rm ~/.gcal_credentials.pickle
rm -rf ~/.config/taskw_gcal_sync/
<rerun your app>
```

**Comment by grovesteyn** [comment]
Thanks.  Got the authentication working again.

Here is my command:

`tw_gcal_sync --taskwarrior-tag "mytag" -c "MyTasks"`

I have exactly one task with the tag "mytag"

Using PDB to print out the json text as you propose shows that it has not applied the tag filter - its a massive long json string with all my tasks.  Here are the last few lines.

`,\n{"id":532,"description":"Doen iets spesiaal vir Ermie","due":"20191117T220000Z","entry":"20191111T114545Z","imask":65,"modified":"20191105T132838Z","parent":"0b1ea6b7-fba7-49bc-98a2-0033b693b267","project":"personal","recur":"weekly","status":"pending","uuid":"8f3efadd-1331-4100-8f19-ca6dd276ed8f","urgency":7.36121}\n]\n'`

Any suggestions?

**Comment by bergercookie** [comment]
Hmm, there doesn't seem to be something weird about this item. Are you sure that's the item that's causing the error?

can you run the program by prefixing it with `python3 -m pdb`? This way you'll get a post-mortem pdb prompt and you'll be able to backtrace in the stack and see what's wrong.

Can you for example, on post-mortem print the *args when _get_json is callled?

```File "/usr/local/lib/python3.6/dist-packages/taskw/warrior.py", line 489, in _get_task_objects
    json = self._get_json(*args)```

**Comment by grovesteyn** [comment]
Hi

I can run the program normally until it fails, but when I run:

`python3 -m pdb tw_gcal_sync -t remindme -c "MyTasks"`

I get:

`Error: tw_gcal_sync does not exist`

Or:

`python3 -m tw_gcal_sync -t remindme -c "MyTasks"`

I get:

`No module named tw_gcal_sync`

I have tried uninstalling tw_gcal_sync and simply reinstalling it from pip, but get the same problem.  Any ideas?

**Comment by grovesteyn** [comment]
> Hmm, there doesn't seem to be something weird about this item. Are you sure that's the item that's causing the error?
> 
> can you run the program by prefixing it with `python3 -m pdb`? This way you'll get a post-mortem pdb prompt and you'll be able to backtrace in the stack and see what's wrong.
> 
> Can you for example, on post-mortem print the *args when _get_json is callled?
> 
> `File "/usr/local/lib/python3.6/dist-packages/taskw/warrior.py", line 489, in _get_task_objects json = self._get_json(*args)`

The point is that this item does NOT have the tag I am filtering for.  It looks like the programme does not apply the tag filter?

**Comment by bergercookie** [comment]
Closing this for now, please reopen if it's still relevant
