### ISSUE TITLE
This works on linux?

### ISSUE THREAD

**Issue by ReK2Fernandez** [bergercookie/taskw_gcal_sync#20]
Im running first time
```
 tw_gcal_sync -t task -c "Tasks"
```
but wont open a browser nor any type of auth and fails because lack of credentials.

```

Traceback (most recent call last):
  File "/home/rek2/.local/bin/tw_gcal_sync", line 71, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/rek2/.local/bin/tw_gcal_sync", line 50, in main
    aggregator.start()
  File "/home/rek2/.local/lib/python3.8/site-packages/taskw_gcal_sync/TWGCalAggregator.py", line 131, in start
    self.gcal_side.start()
  File "/home/rek2/.local/lib/python3.8/site-packages/taskw_gcal_sync/GCalSide.py", line 56, in start
    self.gain_access()
  File "/home/rek2/.local/lib/python3.8/site-packages/taskw_gcal_sync/GCalSide.py", line 214, in gain_access
    creds = self._get_credentials()
  File "/home/rek2/.local/lib/python3.8/site-packages/taskw_gcal_sync/GCalSide.py", line 196, in _get_credentials
    creds.refresh(Request())
  File "/home/rek2/.local/lib/python3.8/site-packages/google/oauth2/credentials.py", line 176, in refresh
    access_token, refresh_token, expiry, grant_response = _client.refresh_grant(
  File "/home/rek2/.local/lib/python3.8/site-packages/google/oauth2/_client.py", line 248, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/rek2/.local/lib/python3.8/site-packages/google/oauth2/_client.py", line 124, in _token_endpoint_request
    _handle_error_response(response_body)
  File "/home/rek2/.local/lib/python3.8/site-packages/google/oauth2/_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_scope: Some requested scopes were invalid. {invalid=[a, c, d, e, g, h, i, l, m, ., n, /, o, p, r, s, t, u, w, :]}', '{\n  "error": "invalid_scope",\n  "error_description": "Some requested scopes were invalid. {invalid\\u003d[a, c, d, e, g, h, i, l, m, ., n, /, o, p, r, s, t, u, w, :]}",\n  "error_uri": "http://code.google.com/apis/accounts/docs/OAuth2.html"\n}')
```

**Comment by bergercookie** [comment]
It should be working on Linux. I'm testing it myself on Linux.
Have you installed  it from github or from Pypi?

I've encountered this error again in [this issue](https://github.com/bergercookie/taskw_gcal_sync/issues/14)

---

Can you first clean the credentials cache and the taskw_gcal_sync config directory and rerun it?

```
rm ~/.gcal_credentials.pickle
rm -rf ~/.config/taskw_gcal_sync/
<rerun your app>
```

**Comment by ReK2Fernandez** [comment]
Yes! is working now thank you
