### ISSUE TITLE
Errors out datetime

### ISSUE THREAD

**Issue by brandoncamenisch** [bergercookie/taskw_gcal_sync#22]
I keep running into what seems like a parsing error. Some of the items are synced and then it fails with something like this...
```
GCalSide: 2020-06-05 12:18:22 - WARNING  - Extra arguments in get_all_items call are not supported yet, ignoring them: {'order_by': None, 'use_ascending_order': True}
taskw_gcal_sync.TWGCalAggregator: 2020-06-05 12:18:26 - INFO     - [gcal] Registering items...
taskw_gcal_sync.TWGCalAggregator: 2020-06-05 12:18:26 - INFO     - [gcal] Inserting item, id: ptge8qgim8976j1665oulot6uc...

TaskWarrior
-----------
        * Tasks created: 0
        * Tasks updated: 0
        * Tasks deleted: 0
        * Errors:        0

Google Calendar
---------------
        * Tasks created: 0
        * Tasks updated: 0
        * Tasks deleted: 0
        * Errors:        0

Traceback (most recent call last):
  File "/home/bc/.local/bin/tw_gcal_sync", line 61, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/bc/.local/bin/tw_gcal_sync", line 53, in main
    aggregator.register_items(gcal_items, "gcal")
  File "/home/bc/.local/lib/python3.8/site-packages/taskw_gcal_sync/TWGCalAggregator.py", line 184, in register_items
    item_converted = convert_fun(item)
  File "/home/bc/.local/lib/python3.8/site-packages/taskw_gcal_sync/TWGCalAggregator.py", line 512, in convert_gcal_to_tw
    tw_item['due'] = GCalSide.get_event_time(gcal_item, t='end')
  File "/home/bc/.local/lib/python3.8/site-packages/taskw_gcal_sync/GCalSide.py", line 227, in get_event_time
    dt = GCalSide.parse_datetime(
  File "/home/bc/.local/lib/python3.8/site-packages/taskw_gcal_sync/GCalSide.py", line 289, in parse_datetime
    assert dot_pos != -1 and \
AssertionError
```

**Comment by bergercookie** [comment]
Hi @brandoncamenisch ,

Did you install this via pypi or directly from the github repo?
If it's the former, could you try installing the latest `master` branch from github and see if the problem persists?

**Comment by brandoncamenisch** [comment]
Awesome @bergercookie installing directly from master how you mentioned got it working.
the pip option with the repo also worked `install --user git+https://github.com/bergercookie/taskw_gcal_sync`


Appreciate your quick feedback and I really look forward to using this :+1:

**Comment by bergercookie** [comment]
OK, I also bumped the pypi version to the latest master so that should also work.
Closing this :)
