### ISSUE TITLE
Error in syncing: KeyError: 'summary'

### ISSUE THREAD

**Issue by WBuddhi** [bergercookie/taskw_gcal_sync#23]
Hi, I'm getting the following errors when running `tw_gcal_sync -t Personal -c <calendar name> `

```
Traceback (most recent call last):
  File "/home/buddhi/.local/bin/tw_gcal_sync", line 71, in <module>
    main()
  File "/home/buddhi/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/buddhi/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/buddhi/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/buddhi/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/buddhi/.local/bin/tw_gcal_sync", line 63, in main
    aggregator.register_items(gcal_items, "gcal")
  File "/home/buddhi/.local/lib/python3.8/site-packages/taskw_gcal_sync/TWGCalAggregator.py", line 185, in register_items
    item_converted = convert_fun(item)
  File "/home/buddhi/.local/lib/python3.8/site-packages/taskw_gcal_sync/TWGCalAggregator.py", line 501, in convert_gcal_to_tw
    tw_item["description"] = gcal_item["summary"]
KeyError: 'summary'
```

I'm also getting timezone related errors during synchronisation:

```
{'summary': 'ELEC4400 L', 'description': 'IMPORTED FROM TASKWARRIOR\n\n* Annotation 1: due_before: today\n\n* status: completed\n* uuid: 0d65c75a-3a53-4850-b828-937e8969d628', 'start': {'dateTime': '2012-07-26T23:00:00.000000Z'}, 'end': {'dateTime': '2012-07-26T23:59:00.000000Z'}, 'updated': '2020-08-23T16:22:27.000000Z'}

Exception: (<class 'googleapiclient.errors.HttpError'>, <HttpError 400 when requesting https://www.googleapis.com/calendar/v3/calendars/w.deseram%40gmail.com/events/tj03rpr2kngngadqg96f1c6nr4?alt=json returned "Missing time zone definition for start time.">, <traceback object at 0x7fcd45b39240>)
```

Could you please help?

**Comment by bergercookie** [comment]
Hi there, the `KeyError: summary` issue should be solved now. Please upgrade using the latest version of master (or devel) branch

Does the second error persist? If so, please create a new issue for it.
