### ISSUE TITLE
If port is used by another application, taskw_gcal_sync fails

### ISSUE THREAD

**Issue by Petemir** [bergercookie/taskw_gcal_sync#27]
Hello,

When I tried to run the app for the first time, I had the following error:

```
Traceback (most recent call last):
  File "/home/petemir/.local/bin/tw_gcal_sync", line 8, in <module>
    sys.exit(main())
  File "/home/petemir/.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/petemir/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/petemir/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/petemir/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/petemir/.local/lib/python3.8/site-packages/taskw_gcal_sync/scripts/tw_gcal_sync.py", line 46, in main
    aggregator.start()
  File "/home/petemir/.local/lib/python3.8/site-packages/taskw_gcal_sync/TWGCalAggregator.py", line 126, in start
    self.gcal_side.start()
  File "/home/petemir/.local/lib/python3.8/site-packages/taskw_gcal_sync/GCalSide.py", line 53, in start
    self.gain_access()
  File "/home/petemir/.local/lib/python3.8/site-packages/taskw_gcal_sync/GCalSide.py", line 209, in gain_access
    creds = self._get_credentials()
  File "/home/petemir/.local/lib/python3.8/site-packages/taskw_gcal_sync/GCalSide.py", line 199, in _get_credentials
    creds = flow.run_local_server()
  File "/home/petemir/.local/lib/python3.8/site-packages/google_auth_oauthlib/flow.py", line 460, in run_local_server
    local_server = wsgiref.simple_server.make_server(
  File "/home/petemir/Apps/anaconda3/envs/newbase/lib/python3.8/wsgiref/simple_server.py", line 154, in make_server
    server = server_class((host, port), handler_class)
  File "/home/petemir/Apps/anaconda3/envs/newbase/lib/python3.8/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/home/petemir/Apps/anaconda3/envs/newbase/lib/python3.8/wsgiref/simple_server.py", line 50, in server_bind
    HTTPServer.server_bind(self)
  File "/home/petemir/Apps/anaconda3/envs/newbase/lib/python3.8/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/petemir/Apps/anaconda3/envs/newbase/lib/python3.8/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
```

I had some docker containers running, I stopped most of them, and then I could run the application without any problems. I couldn't find where the application opens a socket so I don't know what port it is trying to use, but perhaps it would be possible to check if it is used by any application, and if it is, then try another port?

Thanks!

**Comment by bergercookie** [comment]
You can now use the `--oauth-port` flag to change the port that the app is using.
Also there's a clearer message stating which port is in use and what can you do to fix it.

```
  --oauth-port INTEGER            Port to use for oAuth Authentication with
                                  Google Calendar
```
